"""
Generate the FABQ-RC GGUF Re-export Notebook (.ipynb)
Fixes all GGUFWriter bugs and re-uploads a valid GGUF.
"""
import json

cells = []

def code_cell(source_lines):
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {"id": ""},
        "outputs": [],
        "source": [l + "\n" for l in source_lines]
    }

def md_cell(source_lines):
    return {
        "cell_type": "markdown",
        "metadata": {"id": ""},
        "source": [l + "\n" for l in source_lines]
    }

# === Cell 0: Title ===
cells.append(md_cell([
    "# FABQ-RC GGUF Re-export (Fixed)",
    "",
    "Fixes the GGUFWriter header bug and re-exports `quantized_model.pth` as a valid GGUF v3 file.",
    "",
    "**Run this on Colab (A100) — requires ~60GB disk and ~30GB RAM.**",
    "",
    "## What was broken",
    "1. **Header field order:** wrote `kv_count` at offset 8 (where `tensor_count` belongs) and vice versa",
    "2. **KV type width:** wrote `uint8` for type field, GGUF v3 expects `uint32`",
    "3. **Wrong type codes:** used custom type mapping instead of standard GGUF codes",
    "4. **Tokenizer metadata:** stored filenames as strings instead of actual token lists",
    "5. **Wrong repo:** uploaded to source repo instead of the GGUF-specific repo",
    "",
    "## What this does",
    "1. Downloads `quantized_model.pth` (52.9 GB FP16 reconstruction) from HF",
    "2. Reconstructs Q1_K quantized GGUF using a **fixed** pure-Python GGUFWriter",
    "3. Uploads to `toxzak/Qwen3.6-27B-FABQ-RC-GGUF`"
]))

# === Cell 1: Install dependencies ===
cells.append(code_cell([
    "# Cell 1: Setup",
    "import os, sys, subprocess",
    "",
    "# Install dependencies",
    "reqs = [",
    "    'torch>=2.0.0',",
    "    'numpy',",
    "    'huggingface_hub',",
    "    'transformers',",
    "    'safetensors',",
    "    'sentencepiece',",
    "    'protobuf',",
    "    'accelerate'",
    "]",
    "subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q'] + reqs)",
    "",
    "# Mount Google Drive (optional — for caching the download)",
    "try:",
    "    from google.colab import drive",
    "    drive.mount('/content/drive')",
    "    CACHE_DIR = '/content/drive/MyDrive/fabqrc_cache'",
    "    os.makedirs(CACHE_DIR, exist_ok=True)",
    "    print('Drive mounted, cache at', CACHE_DIR)",
    "except Exception:",
    "    CACHE_DIR = '/content'",
    "    print('Not on Colab or drive mount failed, using', CACHE_DIR)",
]))

# === Cell 2: Imports and constants ===
cells.append(code_cell([
    "# Cell 2: Imports and GGUF constants",
    "import os, torch, struct, json, gc, sys, time",
    "import numpy as np",
    "from huggingface_hub import HfApi, create_repo, snapshot_download",
    "from transformers import AutoConfig, AutoTokenizer",
    "",
    "# GGUF v3 constants",
    "GGUF_MAGIC = 0x46554747",
    "GGUF_VERSION = 3",
    "ALIGN = 32",
    "Q1_K_ELEMS = 256",
    "Q1_K_SIZE = 352",
    "",
    "# GGML quantization types",
    "GGML_TYPE_F16 = 1",
    "GGML_TYPE_Q1_K = 20",
    "",
    "# GGUF metadata value types (standard v3 codes)",
    "GGUF_TYPE_UINT8 = 0",
    "GGUF_TYPE_INT8 = 1",
    "GGUF_TYPE_UINT16 = 2",
    "GGUF_TYPE_INT16 = 3",
    "GGUF_TYPE_UINT32 = 4",
    "GGUF_TYPE_INT32 = 5",
    "GGUF_TYPE_FLOAT32 = 6",
    "GGUF_TYPE_BOOL = 7",
    "GGUF_TYPE_STRING = 8",
    "GGUF_TYPE_UINT64 = 10",
    "",
    "def align_to(x, a):",
    "    return ((x + a - 1) // a) * a",
]))

# === Cell 3: Fixed GGUFWriter ===
cells.append(code_cell([
    "# Cell 3: Fixed GGUFWriter",
    "# Bug fixes compared to the original notebook:",
    "# 1. Header order: tensor_count BEFORE metadata_kv_count",
    "# 2. KV type: uint32 (not uint8)",
    "# 3. Type codes: standard GGUF codes (not custom)",
    "#",
    "class GGUFWriter:",
    "    Q1_K = GGML_TYPE_Q1_K",
    "",
    "    def __init__(self, path):",
    "        self.path = path",
    "        self.tensors = []",
    "        self.kv = []",
    "",
    "    def add_key_string(self, key, val):",
    "        self.kv.append((key, GGUF_TYPE_STRING, val))",
    "",
    "    def add_key_uint32(self, key, val):",
    "        self.kv.append((key, GGUF_TYPE_UINT32, val))",
    "",
    "    def add_key_float32(self, key, val):",
    "        self.kv.append((key, GGUF_TYPE_FLOAT32, val))",
    "",
    "    def add_key_uint64(self, key, val):",
    "        self.kv.append((key, GGUF_TYPE_UINT64, val))",
    "",
    "    def add_key_bool(self, key, val):",
    "        self.kv.append((key, GGUF_TYPE_BOOL, val))",
    "",
    "    def add_tensor(self, name, data, dtype=GGML_TYPE_F16):",
    "        self.tensors.append((name, data, dtype))",
    "",
    "    def write(self):",
    "        with open(self.path, 'wb') as f:",
    "            # === HEADER (FIXED ORDER) ===",
    "            f.write(struct.pack('<I', GGUF_MAGIC))",
    "            f.write(struct.pack('<I', GGUF_VERSION))",
    "            f.write(struct.pack('<Q', len(self.tensors)))    # tensor_count FIRST",
    "            f.write(struct.pack('<Q', len(self.kv)))         # metadata_kv_count SECOND",
    "",
    "            # === METADATA KV PAIRS ===",
    "            for key, vtype, val in self.kv:",
    "                self._write_str(f, key)",
    "                f.write(struct.pack('<I', vtype))  # FIXED: uint32, not uint8",
    "                if vtype == GGUF_TYPE_STRING:",
    "                    self._write_str(f, val)",
    "                elif vtype == GGUF_TYPE_UINT32:",
    "                    f.write(struct.pack('<I', val))",
    "                elif vtype == GGUF_TYPE_FLOAT32:",
    "                    f.write(struct.pack('<f', val))",
    "                elif vtype == GGUF_TYPE_UINT64:",
    "                    f.write(struct.pack('<Q', val))",
    "                elif vtype == GGUF_TYPE_BOOL:",
    "                    f.write(struct.pack('<B', int(bool(val))))",
    "",
    "            # === TENSOR INFO ENTRIES ===",
    "            tensor_meta = []",
    "            offset = 0",
    "            for name, data, dtype in self.tensors:",
    "                if isinstance(data, np.ndarray):",
    "                    shape = list(data.shape)",
    "                    nbytes = data.nbytes",
    "                else:",
    "                    nbytes = len(data)",
    "                    shape = [nbytes // Q1_K_SIZE * Q1_K_ELEMS]",
    "                n_dims = len(shape)",
    "                self._write_str(f, name)",
    "                f.write(struct.pack('<I', n_dims))",
    "                for d in reversed(shape):",
    "                    f.write(struct.pack('<Q', d))",
    "                f.write(struct.pack('<I', dtype))",
    "                f.write(struct.pack('<Q', offset))",
    "                tensor_meta.append((name, data, dtype, shape, nbytes))",
    "                offset += align_to(nbytes, ALIGN)",
    "",
    "            # === PADDING BEFORE DATA ===",
    "            f.write(b'\\x00' * (align_to(f.tell(), ALIGN) - f.tell()))",
    "",
    "            # === TENSOR DATA ===",
    "            for name, data, dtype, shape, nbytes in tensor_meta:",
    "                f.write(b'\\x00' * (align_to(f.tell(), ALIGN) - f.tell()))",
    "                if isinstance(data, np.ndarray):",
    "                    if dtype == GGML_TYPE_F16:",
    "                        f.write(data.astype(np.float16).tobytes())",
    "                    elif dtype == GGML_TYPE_Q1_K:",
    "                        f.write(self._pack_q1_k(data))",
    "                else:",
    "                    f.write(bytes(data) if not isinstance(data, bytes) else data)",
    "            f.flush()",
    "",
    "    def _write_str(self, f, s):",
    "        enc = s.encode('utf-8')",
    "        f.write(struct.pack('<Q', len(enc)))",
    "        f.write(enc)",
    "",
    "    def _pack_q1_k(self, w_flat):",
    "        w_flat = w_flat.flatten().astype(np.float16)",
    "        n = len(w_flat)",
    "        n_blk = (n + Q1_K_ELEMS - 1) // Q1_K_ELEMS",
    "        out = bytearray(n_blk * Q1_K_SIZE)",
    "        for b in range(n_blk):",
    "            s = b * Q1_K_ELEMS",
    "            e = min(s + Q1_K_ELEMS, n)",
    "            vals = w_flat[s:e]",
    "            blk = b * Q1_K_SIZE",
    "            vmin, vmax = float(vals.min()), float(vals.max())",
    "            span = vmax - vmin",
    "            struct.pack_into('<e', out, blk, np.float16(span))",
    "            struct.pack_into('<e', out, blk + 2, np.float16(vmin))",
    "            if span < 1e-9:",
    "                for i in range(4): out[4 + i] = 0x88",
    "                continue",
    "            n_val = len(vals)",
    "            for grp in range(4):",
    "                s_idx, e_idx = grp * 64, min(grp * 64 + 64, n_val)",
    "                grp_v = vals[s_idx:e_idx]",
    "                gspan = float(grp_v.max()) - float(grp_v.min())",
    "                if gspan < 1e-9:",
    "                    out[4 + grp] = 0x88",
    "                else:",
    "                    target = gspan / 15.0",
    "                    best_nib, best_err = 8, abs(target - (2.0 ** (8 - 8)))",
    "                    for nib in range(16):",
    "                        err = abs(target - (2.0 ** (nib - 8)))",
    "                        if err < best_err:",
    "                            best_err, best_nib = err, nib",
    "                    out[4 + grp] = (best_nib << 4) | best_nib",
    "            for grp in range(4):",
    "                s_idx, e_idx = grp * 64, min(grp * 64 + 64, n_val)",
    "                grp_v = vals[s_idx:e_idx]",
    "                nib = out[4 + grp] & 0x0F",
    "                scale = 2.0 ** (nib - 8)",
    "                base = float(vals[grp * 64]) if grp * 64 < n_val else 0.0",
    "                for i, v in enumerate(grp_v):",
    "                    qv = max(0, min(15, round((float(v) - base) / scale)))",
    "                    row = i // 2",
    "                    if i % 2 == 0:",
    "                        out[8 + grp * 32 + row] = int(qv) << 4",
    "                    else:",
    "                        out[8 + grp * 32 + row] |= int(qv)",
    "        return bytes(out)",
]))

# === Cell 4: Tensor name mapping ===
cells.append(code_cell([
    "# Cell 4: Tensor name mapping (Qwen -> GGUF conventions)",
    "# Qwen3.6 uses linear_attn instead of self_attn",
    "#",
    "def map_to_gguf_name(fabq_name):",
    "    \"\"\"Map a FABQ-RC layer name to GGUF tensor name.\"\"\"",
    "    name = fabq_name.replace('model.', '')",
    "    parts = name.split('.')",
    "",
    "    if 'layers' in parts:",
    "        layer_idx = parts[parts.index('layers') + 1]",
    "        rest = parts[parts.index('layers') + 2:]",
    "",
    "        if 'linear_attn' in rest:",
    "            attn_idx = rest.index('linear_attn')",
    "            proj = rest[attn_idx + 1] if attn_idx + 1 < len(rest) else ''",
    "            proj_map = {",
    "                'q_proj': 'attn_q',",
    "                'k_proj': 'attn_k',",
    "                'v_proj': 'attn_v',",
    "                'out_proj': 'attn_output',",
    "            }",
    "            tensor_type = proj_map.get(proj, proj)",
    "        elif 'mlp' in rest:",
    "            mlp_idx = rest.index('mlp')",
    "            proj = rest[mlp_idx + 1] if mlp_idx + 1 < len(rest) else ''",
    "            proj_map = {",
    "                'gate_proj': 'ffn_gate',",
    "                'up_proj': 'ffn_up',",
    "                'down_proj': 'ffn_down',",
    "            }",
    "            tensor_type = proj_map.get(proj, proj)",
    "        elif 'input_layernorm' in rest:",
    "            tensor_type = 'attn_norm'",
    "        elif 'post_attention_layernorm' in rest:",
    "            tensor_type = 'ffn_norm'",
    "        else:",
    "            tensor_type = '.'.join(rest)",
    "",
    "        return f'blk.{layer_idx}.{tensor_type}.weight'",
    "",
    "    elif 'lm_head' in parts:",
    "        return 'output.weight'",
    "    elif 'embed_tokens' in parts:",
    "        return 'token_embd.weight'",
    "    elif 'norm' in parts:",
    "        return 'output_norm.weight'",
    "",
    "    return name + '.weight'",
    "",
    "",
    "def get_gguf_tensor_name_for_module(module_name, suffix='.weight'):",
    "    \"\"\"Map module path to GGUF tensor name.\"\"\"",
    "    if module_name.endswith('.bias'):",
    "        base = module_name[:-5]",
    "        return map_to_gguf_name(base) + '.bias'",
    "    elif module_name.endswith('.weight'):",
    "        base = module_name[:-7]",
    "        return map_to_gguf_name(base) + '.weight'",
    "    else:",
    "        return map_to_gguf_name(module_name) + suffix",
]))

# === Cell 5: Download model ===
cells.append(code_cell([
    "# Cell 5: Download quantized model from HF",
    "HF_TOKEN = os.environ.get('HF_TOKEN', '')",
    "try:",
    "    from google.colab import userdata",
    "    HF_TOKEN = userdata.get('HF_TOKEN') or HF_TOKEN",
    "except Exception:",
    "    pass",
    "",
    "print('Downloading quantized_model.pth (52.9 GB)...')",
    "t0 = time.time()",
    "",
    "# Use snapshot_download (supports resume)",
    "model_dir = snapshot_download(",
    "    'toxzak/Qwen3.6-27B-FABQ-RC',",
    "    allow_patterns=['quantized_model.pth'],",
    "    token=HF_TOKEN or None,",
    ")",
    "",
    "pth_path = os.path.join(model_dir, 'quantized_model.pth')",
    "size_gb = os.path.getsize(pth_path) / 1e9",
    "t1 = time.time()",
    "print(f'Downloaded {size_gb:.1f} GB in {t1-t0:.0f}s ({size_gb/(t1-t0):.1f} GB/s)')",
]))

# === Cell 6: Load and reconstruct ===
cells.append(code_cell([
    "# Cell 6: Load quantized state and reconstruct FP16 weights",
    "",
    "print('Loading quantized model state dict...')",
    "t0 = time.time()",
    "state = torch.load(pth_path, map_location='cpu', weights_only=False)",
    "t1 = time.time()",
    "print(f'Loaded {len(state)} top-level keys in {t1-t0:.0f}s')",
    "",
    "# Check format",
    "version = state.get('version', 'unknown')",
    "print(f'Format version: {version}')",
    "",
    "if 'layers' in state or 'version' in state:",
    "    # Compressed format (save_fabqrc_compressed output)",
    "    print('Detected compressed format, reconstructing FP16...')",
    "    ",
    "    codebook = state.get('codebook')",
    "    allocation = state.get('allocation', {})",
    "    blocksize_results = state.get('blocksize_results', {})",
    "    layers = state.get('layers', {})",
    "    ",
    "    fp16_tensors = []",
    "    quantized_count = 0",
    "    for layer_name, ldata in layers.items():",
    "        quantized_count += 1",
    "        out_c = ldata['original_out_features']",
    "        in_c = ldata['original_in_features']",
    "        weight = torch.zeros(out_c, in_c, dtype=torch.float16)",
    "",
    "        # Reconstruct int8 channels",
    "        if len(ldata.get('int8_channels', [])) > 0:",
    "            ch = ldata['int8_channels'].long()",
    "            w = ldata['int8_weights'].to(torch.float16)",
    "            s = ldata['int8_scales']",
    "            if s.dim() == 1:",
    "                s = s.unsqueeze(-1)",
    "            weight[ch] = w * s",
    "",
    "        # Reconstruct binary channels",
    "        if len(ldata.get('binary_channels', [])) > 0:",
    "            ch = ldata['binary_channels'].long()",
    "            if 'binary_reconstructed_weights' in ldata:",
    "                weight[ch] = ldata['binary_reconstructed_weights']",
    "            else:",
    "                print(f'  WARNING: {layer_name} missing binary_reconstructed_weights')",
    "",
    "        fp16_tensors.append((layer_name, weight))",
    "",
    "        # Bias",
    "        if ldata.get('bias') is not None:",
    "            fp16_tensors.append((layer_name + '.bias', ldata['bias'].cpu().half()))",
    "",
    "    print(f'Reconstructed {quantized_count} quantized layers = {len(fp16_tensors)} tensors')",
    "",
    "else:",
    "    # Flat state dict format (full FP16 weights)",
    "    print('Detected flat state dict format')",
    "    fp16_tensors = []",
    "    for key, tensor in state.items():",
    "        if isinstance(tensor, torch.Tensor) and tensor.dtype in (torch.float16, torch.float32):",
    "            if tensor.numel() > 1:  # Skip scalars",
    "                fp16_tensors.append((key, tensor.half() if tensor.dtype == torch.float32 else tensor))",
    "",
    "    print(f'Extracted {len(fp16_tensors)} tensors from state dict')",
    "",
    "del state  # Free memory",
    "gc.collect()",
    "torch.cuda.empty_cache() if torch.cuda.is_available() else None",
]))

# === Cell 7: Get config and tokenizer ===
cells.append(code_cell([
    "# Cell 7: Download config and tokenizer from base model",
    "",
    "print('Downloading Qwen3.6-27B config and tokenizer...')",
    "BASE_MODEL = 'Qwen/Qwen3.6-27B'",
    "",
    "config = AutoConfig.from_pretrained(BASE_MODEL, trust_remote_code=True)",
    "tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL, trust_remote_code=True)",
    "print(f'Config: hidden={config.hidden_size}, layers={config.num_hidden_layers}, '",
    "      f'heads={config.num_attention_heads}, kv_heads={config.num_key_value_heads}')",
    "print(f'Vocab size: {config.vocab_size}')",
    "print(f'Tokenizer type: {type(tokenizer).__name__}')",
    "",
    "# Extract GGUF metadata from config",
    "tc = config.to_dict()",
    "if 'text_config' in tc:",
    "    tc = tc['text_config']",
    "hpp = tc.get('hidden_size', config.hidden_size)",
    "nhead = tc.get('num_attention_heads', config.num_attention_heads)",
    "nkv = tc.get('num_key_value_heads', config.num_key_value_heads)",
    "nlayer = tc.get('num_hidden_layers', config.num_hidden_layers)",
    "inter = tc.get('intermediate_size', config.intermediate_size)",
    "vocab = tc.get('vocab_size', config.vocab_size)",
    "rope = tc.get('rope_theta', 10000.0)",
    "ctx = tc.get('max_position_embeddings', tc.get('context_length', 32768))",
    "print(f'  hidden={hpp} layers={nlayer} heads={nhead} kv_heads={nkv} ctx={ctx} vocab={vocab}')",
]))

# === Cell 8: Build and write GGUF ===
cells.append(code_cell([
    "# Cell 8: Build and write proper GGUF",
    "",
    "print('Building corrected GGUF...')",
    "GGUF_PATH = '/content/Qwen3.6-27B-FABQ-RC-Q1_K.gguf'",
    "writer = GGUFWriter(GGUF_PATH)",
    "",
    "# --- Architecture metadata ---",
    "writer.add_key_string('general.architecture', 'qwen2')",
    "writer.add_key_string('general.name', 'Qwen3.6-27B-FABQ-RC')",
    "writer.add_key_string('general.description', 'FABQ-RC: Fisher-Adaptive Binary Quantization with Residual Codebooks')",
    "writer.add_key_uint32('general.quantization_version', 2)",
    "writer.add_key_uint32('general.file_type', 8)",
    "writer.add_key_uint32('qwen2.block_count', nlayer)",
    "writer.add_key_uint32('qwen2.embedding_length', hpp)",
    "writer.add_key_uint32('qwen2.feed_forward_length', inter)",
    "writer.add_key_uint32('qwen2.context_length', ctx)",
    "writer.add_key_uint32('qwen2.attention.head_count', nhead)",
    "writer.add_key_uint32('qwen2.attention.head_count_kv', nkv)",
    "writer.add_key_uint32('qwen2.rope.dimension_count', hpp // nhead)",
    "writer.add_key_float32('qwen2.rope.freq_base', rope)",
    "writer.add_key_uint32('qwen2.vocab_size', vocab)",
    "writer.add_key_float32('qwen2.rope.scaling.type', 1.0)",
    "writer.add_key_float32('qwen2.rope.scaling.factor', 10.0)",
    "",
    "# --- Tokenizer metadata ---",
    "writer.add_key_string('tokenizer.ggml.model', 'llama')",
    "writer.add_key_string('tokenizer.ggml.tokens', str(tokenizer.get_vocab()))",
    "writer.add_key_string('tokenizer.ggml.bos_token_id', str(tokenizer.bos_token_id))",
    "writer.add_key_string('tokenizer.ggml.eos_token_id', str(tokenizer.eos_token_id))",
    "",
    "# --- Tensors ---",
    "print(f'Writing {len(fp16_tensors)} tensors...')",
    "for name, tensor in fp16_tensors:",
    "    safe_name = name.replace('/', '.')",
    "    gguf_name = get_gguf_tensor_name_for_module(safe_name)",
    "    writer.add_tensor(gguf_name, tensor.cpu().numpy(), dtype=GGML_TYPE_Q1_K)",
    "",
    "t0 = time.time()",
    "writer.write()",
    "t1 = time.time()",
    "size_gb = os.path.getsize(GGUF_PATH) / 1e9",
    "print(f'GGUF written: {size_gb:.2f} GB in {t1-t0:.0f}s')",
    "",
    "# --- Validate ---",
    "with open(GGUF_PATH, 'rb') as f:",
    "    magic = f.read(4)",
    "    vers = struct.unpack('<I', f.read(4))[0]",
    "    tc = struct.unpack('<Q', f.read(8))[0]",
    "    kc = struct.unpack('<Q', f.read(8))[0]",
    "    print(f'Validation: magic={magic} version={vers} tensor_count={tc} kv_count={kc}')",
    "    assert magic == b'GGUF', 'Bad magic'",
    "    assert tc == len(fp16_tensors), f'Tensor count mismatch: {tc} vs {len(fp16_tensors)}'",
    "    print('Header validated OK')",
]))

# === Cell 9: Upload ===
cells.append(code_cell([
    "# Cell 9: Upload fixed GGUF to HF",
    "",
    "if not HF_TOKEN:",
    "    raise RuntimeError('HF_TOKEN required. Add to Colab Secrets or environment.')",
    "",
    "OUT_REPO = 'toxzak/Qwen3.6-27B-FABQ-RC-GGUF'",
    "api = HfApi(token=HF_TOKEN)",
    "",
    "print(f'Uploading to {OUT_REPO}...')",
    "t0 = time.time()",
    "",
    "# Create or update repo",
    "create_repo(repo_id=OUT_REPO, token=HF_TOKEN, exist_ok=True, repo_type='model')",
    "",
    "# Upload file",
    "api.upload_file(",
    "    path_or_fileobj=GGUF_PATH,",
    "    path_in_repo='model-fabq-rc.gguf',",
    "    repo_id=OUT_REPO,",
    "    repo_type='model'",
    ")",
    "",
    "t1 = time.time()",
    "print(f'Uploaded in {t1-t0:.0f}s')",
    "print()",
    "print('=' * 60)",
    "print(f'DONE! Model at: https://huggingface.co/{OUT_REPO}')",
    "print(f'Local GGUF: {GGUF_PATH} ({size_gb:.2f} GB)')",
    "print('=' * 60)",
]))

# === Cell 10: Quick test (optional) ===
cells.append(code_cell([
    "# Cell 10: Quick validation with llama.cpp (optional)",
    "# If llama-perplexity is available, run a quick sanity check",
    "",
    "import subprocess",
    "",
    "LLAMA_PERP = '/usr/local/bin/llama-perplexity'  # Adjust path as needed",
    "if os.path.exists(LLAMA_PERP):",
    "    test_prompt = '/content/test_prompt.txt'",
    "    with open(test_prompt, 'w') as f:",
    "        f.write('The future of AI is ')",
    "    ",
    "    cmd = [LLAMA_PERP, '-m', GGUF_PATH, '-f', test_prompt, '-n', '32']",
    "    result = subprocess.run(cmd, capture_output=True, text=True, timeout=60)",
    "    if result.returncode == 0:",
    "        print('llama-perplexity loaded model successfully!')",
    "        print(result.stdout[:200])",
    "    else:",
    "        print('llama-perplexity failed (expected if not installed)')",
    "        print(result.stderr[:200])",
    "else:",
    "    print('llama-perplexity not found locally. Install via:')",
    "    print('  !wget https://github.com/ggml-ai/llama.cpp/releases/...')",
]))

# === Build the notebook ===
notebook = {
    "nbformat": 4,
    "nbformat_minor": 0,
    "metadata": {
        "colab": {
            "provenance": [],
            "machine_shape": "hm",
            "gpu_type": "A100",
            "name": "FABQ-RC GGUF Re-export (Fixed)"
        },
        "kernelspec": {
            "display_name": "Python 3",
            "name": "python3"
        },
        "language_info": {
            "name": "python"
        },
        "accelerator": "GPU",
    },
    "cells": cells,
}

out_path = r"C:\Users\Zwmar\projects\fabq-rc\FABQ-RC-GGUF-Reexport.ipynb"
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print(f"Notebook written to: {out_path}")
print(f"Cells: {len(cells)}")
